# Build Stage 
FROM --platform=linux/amd64 node:20-alpine as build
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --omit-dev
# Run Stage
FROM nginx:1.17.1-alpine
COPY --from=build app/dist/client /usr/share/nginx/html
COPY --from=build app/compose-nginx-proxy.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]