version: '3.7'
services:
  carpoolapi:
    build: ./api/.
    container_name: carpoolAPI
    ports:
      - "5550:5550"
    environment: 
      BASE_URL : ":5550"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      ConnectionString: "mongodb://{username}:{password}@mongo:27017"
      DatabaseName: carpool
      DbUserName: mongoadmin
      DbPassword: secret
    networks:
      - carpool-network
    depends_on:
      - mongo
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: carpool_jaeger
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - carpool-network      
  prometheus:
    build: prometheus/.
    container_name: carpool_prometheus
    networks:
      - carpool-network    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on: 
      - prometheus  
    networks:
      - carpool-network      
  mongo:
    build: ./mongodb/.
    container_name: carpool-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: carpool
    volumes: 
      - carpool-mongodata:/data/db
    networks:
      - carpool-network
  mongo-express:
    image: mongo-express
    container_name: carpool-mexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongo:27017/
    depends_on: 
      - mongo
    networks:
      - carpool-network
networks:
  carpool-network:    
volumes:
  carpool-mongodata:
  grafana-storage:
