############################
# STEP 1 build executable binary
############################
FROM golang:alpine AS builder
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/carpool/
COPY . .
# Fetch dependencies. Install go-swagger package to automate the generation of RESTful API documentation.
RUN go install github.com/go-swagger/go-swagger/cmd/swagger
# Using go get.
RUN go get -d -v
# Build the binary.
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o /go/bin/carpool
# Generate the RESTful API documentation.
RUN swagger generate spec -o /go/bin/swagger.yaml --scan-models
############################
# STEP 2 build a small image
############################
FROM scratch
# Copy our static executable.
COPY --from=builder /go/bin/carpool /go/bin/carpool
WORKDIR /go/bin/
ADD static/version.txt /go/bin/static/version.txt
ADD configuration/livesettings.json /go/bin/configuration/livesettings.json
COPY --from=builder /go/bin/swagger.yaml /go/bin/swagger.yaml
ENV BASE_URL :5550
ENV JAEGER_SERVICE_NAME carpool
# Run the hello binary.
ENTRYPOINT ["/go/bin/carpool"]